name: CI Release
on:
  push:
    branches:
      - "**"
      - "!main"
      - "!next"
jobs:
  general:
    name: General Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Pnpm Setup
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: db generate
        run: pnpm db:generate
      - name: Test
        run: pnpm test
      - name: Lint
        run: pnpm lint
